# -*- coding: utf-8 -*-
"""task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XjrbfW5Nf7zWDzAUhOXRjW0RQQ6x-TI

**Task 07: Querying RDF(s)**
"""

# pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
result = [] #list of tuples
for clase in g.subjects(RDF.type, RDFS.Class):
  super = g.value(clase, RDFS.subClassOf)
  if super:
    result.append((clase, super))
  else:
    result.append((clase,None))
print(result)
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?c ?sc WHERE {
  ?c rdf:type rdfs:Class .
  OPTIONAL {
    ?c rdfs:subClassOf ?sc .
  }
} """

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []
def is_person_subclass(cls):
    if cls == ns.Person:
        return True
    for s, p, o in g.triples((cls, RDFS.subClassOf, None)):
        if is_person_subclass(o):
            return True
    return False
for s, p, o in g.triples((None, RDF.type, None)):
    if o == ns.Person or is_person_subclass(o):
        individuals.append(s)# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """
PREFIX ppl: <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?ind
WHERE {
  ?p rdfs:subClassOf* ppl:Person .
  ?ind a ?p .
  }"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

# TO DO
query = """
PREFIX ppl: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name ?type WHERE {
  ?p ppl:knows ppl:Rocky .
  ?p rdfs:label ?name .
  ?p rdf:type ?type .
}
"""
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """
PREFIX ppl: <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?name WHERE {
  ?p rdfs:label ?name .
  {
    ?p ppl:hasColleague ?colleague1 .
    ?colleague1 ppl:ownsPet ?pet1 .
  } UNION {
    ?p ppl:hasColleague ?colleague1 .
    ?colleague1 ppl:hasColleague ?colleague2 .
    ?colleague2 ppl:ownsPet ?pet2 .
  }
}
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")