# -*- coding: utf-8 -*-
"""task07.py

Automatically generated by Colab.
"""

#!pip install rdflib  # Comentada según instrucciones

from validation import Report

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS

g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"
g.parse(github_storage + "/rdf/data06.ttl", format="ttl")

report = Report()

result = []

for cls in g.subjects(RDF.type, RDFS.Class):
    super_cls = None
    for sc in g.objects(cls, RDFS.subClassOf):
        super_cls = sc
    result.append((cls, super_cls))

for r in result:
    print(r)

report.validate_07_1a(result)

query = """
SELECT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc }
}
"""

for r in g.query(query):
    print(r.c, r.sc)

report.validate_07_1b(query, g)

from rdflib import RDF, RDFS, Namespace

ns = Namespace("http://oeg.fi.upm.es/def/people#")
individuals = []

def get_all_subclasses(cls, graph):
    subclasses = set()
    for subclass in graph.subjects(RDFS.subClassOf, cls):
        subclasses.add(subclass)
        subclasses.update(get_all_subclasses(subclass, graph))
    return subclasses

all_person_classes = set([ns.Person])
all_person_classes.update(get_all_subclasses(ns.Person, g))

for cls in all_person_classes:
    for ind in g.subjects(RDF.type, cls):
        if ind not in individuals:
            individuals.append(ind)

for i in individuals:
    print(i)

report.validate_07_02a(individuals)

query = """
SELECT ?ind
WHERE {
  ?ind a/rdfs:subClassOf* <http://oeg.fi.upm.es/def/people#Person> .
}
"""

for r in g.query(query):
    print(r.ind)

report.validate_07_02b(g, query)

query = """
SELECT ?name ?type
WHERE {
  ?person <http://oeg.fi.upm.es/def/people#knows> <http://oeg.fi.upm.es/def/people#Rocky> .
  ?person <http://www.w3.org/2000/01/rdf-schema#label> ?name .
  ?person a ?type .
}
"""

for r in g.query(query):
    print(r.name, r.type)

report.validate_07_03(g, query)

query = """
SELECT ?name ?type
WHERE {
  ?person <http://oeg.fi.upm.es/def/people#knows> <http://oeg.fi.upm.es/def/people#Rocky> .
  ?person rdfs:label ?name .
  ?person a ?type .
}
"""

for r in g.query(query):
    print(r.name, r.type)

report.validate_07_03(g, query)

query = """
SELECT DISTINCT ?ind
WHERE {
  ?ind a ?class .
  ?class rdfs:subClassOf* <http://oeg.fi.upm.es/def/people#Person> .
}
"""

individuals = []
for r in g.query(query):
    individuals.append(r.ind)
    print(r.ind)

report.validate_07_02b(g, query)


report.save_report("_Task_07")
