PREFIX  mod: <https://w3id.org/mod#> .
PREFIX  ns: <http://movimientosostenible.org/group14#> .
PREFIX  owl: <http://www.w3.org/2002/07/owl#> .
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#> .

#1 todas las tripletas
SELECT ?s ?p ?o 
WHERE { 
?s ?p ?o 
}
LIMIT 20

#2
SELECT ?accidente ?tipo
WHERE {
    ?accidente a <ns:Accidente> ;
               <ns:tipoAccidente> ?tipo .
}
LIMIT 20

#3
SELECT ?accidente
WHERE {
    ?accidente a <ns:Accidente> ;
}
LIMIT 20

#4
SELECT ?accidente ?uri
WHERE {
    ?accidente owl:sameAs ?uri .
}


